from .alloc import *
from .controlflow import *
from .debug import *
from .indexing import *
from .magik import *
from .math import *
from .shapes import *
from .types import *
from .various import *

from . import alloc
from . import controlflow
from . import debug
from . import indexing
from . import magik
from . import symbolik
from . import math
from . import shapes
from . import types
from . import various
